<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="1" ignored="0" total="10" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="216125" started-at="2020-05-15T11:11:36 IST" finished-at="2020-05-15T11:15:12 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="216125" started-at="2020-05-15T11:11:36 IST" finished-at="2020-05-15T11:15:12 IST">
      <class name="testing.AccountTest">
        <test-method status="PASS" signature="Invalid()[pri:1, instance:testing.AccountTest@2344fc66]" name="Invalid" duration-ms="28554" started-at="2020-05-15T11:11:36 IST" finished-at="2020-05-15T11:12:04 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Invalid -->
        <test-method status="PASS" signature="Forgotpassword()[pri:2, instance:testing.AccountTest@2344fc66]" name="Forgotpassword" duration-ms="4119" started-at="2020-05-15T11:12:04 IST" depends-on-methods="testing.LoginTest.Invalid" finished-at="2020-05-15T11:12:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Forgotpassword -->
        <test-method status="PASS" signature="singin()[pri:3, instance:testing.AccountTest@2344fc66]" name="singin" duration-ms="7748" started-at="2020-05-15T11:12:09 IST" depends-on-methods="testing.LoginTest.Forgotpassword" finished-at="2020-05-15T11:12:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- singin -->
        <test-method status="PASS" signature="over()[pri:4, instance:testing.AccountTest@2344fc66]" name="over" duration-ms="118608" started-at="2020-05-15T11:12:16 IST" depends-on-methods="testing.LoginTest.singin" finished-at="2020-05-15T11:14:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- over -->
        <test-method status="PASS" signature="Appoint()[pri:5, instance:testing.AccountTest@2344fc66]" name="Appoint" duration-ms="29220" started-at="2020-05-15T11:14:15 IST" depends-on-methods="testing.OverviewTest.over" finished-at="2020-05-15T11:14:44 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Appoint -->
        <test-method status="FAIL" signature="schedule()[pri:6, instance:testing.AccountTest@2344fc66]" name="schedule" duration-ms="27805" started-at="2020-05-15T11:14:44 IST" depends-on-methods="testing.AppointmentTest.Appoint" finished-at="2020-05-15T11:15:12 IST">
          <exception class="org.openqa.selenium.StaleElementReferenceException">
            <message>
              <![CDATA[The element reference of <button id="5_84" class="table-btn-primary time_slot_button Friday active" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'LAPTOP-NL1EMSF5', ip: '192.168.43.31', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 75.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200403170909, moz:geckodriverVersion: 0.26.0, moz:headless: false, moz:processID: 14420, moz:profile: C:\Users\Arbina\AppData\Loc..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: dd5c7289-26f8-439d-b17b-09a43252c4df]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.StaleElementReferenceException: The element reference of <button id="5_84" class="table-btn-primary time_slot_button Friday active" type="button"> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'LAPTOP-NL1EMSF5', ip: '192.168.43.31', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 75.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200403170909, moz:geckodriverVersion: 0.26.0, moz:headless: false, moz:processID: 14420, moz:profile: C:\Users\Arbina\AppData\Loc..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: dd5c7289-26f8-439d-b17b-09a43252c4df
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at testing.SchedulesTest.schedule(SchedulesTest.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.TestNG.privateMain(TestNG.java:1363)
at org.testng.TestNG.main(TestNG.java:1331)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.StaleElementReferenceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method status="SKIP" signature="patients()[pri:7, instance:testing.AccountTest@2344fc66]" name="patients" duration-ms="0" started-at="2020-05-15T11:15:12 IST" depends-on-methods="testing.SchedulesTest.schedule" finished-at="2020-05-15T11:15:12 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PatientTest.patients()[pri:7, instance:testing.AccountTest@2344fc66] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PatientTest.patients()[pri:7, instance:testing.AccountTest@2344fc66] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.TestNG.privateMain(TestNG.java:1363)
at org.testng.TestNG.main(TestNG.java:1331)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- patients -->
        <test-method status="SKIP" signature="Specialist()[pri:8, instance:testing.AccountTest@2344fc66]" name="Specialist" duration-ms="0" started-at="2020-05-15T11:15:12 IST" depends-on-methods="testing.PatientTest.patients" finished-at="2020-05-15T11:15:12 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SearchTest.Specialist()[pri:8, instance:testing.AccountTest@2344fc66] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SearchTest.Specialist()[pri:8, instance:testing.AccountTest@2344fc66] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.TestNG.privateMain(TestNG.java:1363)
at org.testng.TestNG.main(TestNG.java:1331)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Specialist -->
        <test-method status="SKIP" signature="Resource()[pri:9, instance:testing.AccountTest@2344fc66]" name="Resource" duration-ms="0" started-at="2020-05-15T11:15:12 IST" depends-on-methods="testing.PatientTest.patients" finished-at="2020-05-15T11:15:12 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method ResourcesTest.Resource()[pri:9, instance:testing.AccountTest@2344fc66] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method ResourcesTest.Resource()[pri:9, instance:testing.AccountTest@2344fc66] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.TestNG.privateMain(TestNG.java:1363)
at org.testng.TestNG.main(TestNG.java:1331)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Resource -->
        <test-method status="SKIP" signature="Profile()[pri:10, instance:testing.AccountTest@2344fc66]" name="Profile" duration-ms="0" started-at="2020-05-15T11:15:12 IST" depends-on-methods="testing.ResourcesTest.Resource" finished-at="2020-05-15T11:15:12 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AccountTest.Profile()[pri:10, instance:testing.AccountTest@2344fc66] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AccountTest.Profile()[pri:10, instance:testing.AccountTest@2344fc66] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.TestNG.privateMain(TestNG.java:1363)
at org.testng.TestNG.main(TestNG.java:1331)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Profile -->
      </class> <!-- testing.AccountTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
